### ISSUE TITLE
Problem loading datatables JS breaks javascript for site

### ISSUE THREAD

**Issue by moodleulpgc** [marcusgreen/moodle-report_advancedgrading#9] opened 2023-05-30 15:28 UTC
Hi, I have found that this plugin breaks javascript in my site, making navigation unusable. 

Working with theme moove or boost, having this plugin installed makes the site unusable due to JS not working, so navigation stops to work. 

When viewing the page  https://localhost/moodle41ulpgc/report/advancedgrading/rubric.php
the browser JS console has the mesasge

The resource “https://localhost/moodle41ulpgc/lib/requirejs.php/-1/datatables.net.js” was blocked due to discondance on MIME type (“text/html”) (X-Content-Type-Options: nosniff).

 Uncaught Error: Script error for "datatables.net", needed by: core/menu_navigation
http://requirejs.org/docs/errors.html#scripterror

**Comment by marcusgreen** [comment] 2023-05-30 15:35
Thank you for reporting this (and especially the console message) Can you go to settings and uncheck
enable_javascriptlayout
And let me know if the issue goes away.

**Comment by moodleulpgc** [comment] 2023-05-30 16:20
Hi Marcus:  NO the setting enable_javascriptlayout makes no effect. The navigation is broken both with that enable or disabled.  The problem is there, it doesn't go away.

Actually, a grep in the code locates NO use for that setting in the report_advancedgrading folder. Only referenced in settings and in lang, no actual code, PHP or JS seems to be using it. 

I've been able to avoid the problem only by removing  completely the amd folder.  
Even keeping the amd folder and commenting out 
$PAGE->requires->js_call_amd('report_advancedgrading/table_sort', 'init'); 
makes NO effect.

Other assignments, with other rubrics and different status (other submissions settings, graded and ungraded students) show other errors in the browser console, for instance

 Uncaught Error: No define call for report_advancedgrading/table_sort
http://requirejs.org/docs/errors.html#nodefine

[event.js:5189:91082](https://cvdev.ulpgc.es/moodle4test/lib/requirejs.php/1685461410/core/event.js)
 Uncaught TypeError: a is undefined
    e https://cvdev.ulpgc.es/moodle4test/lib/requirejs.php/1685461410/core/event.js:5189
    <anonymous> https://cvdev.ulpgc.es/moodle4test/lib/requirejs.php/1685461410/core/event.js:5189
    <anonymous> https://cvdev.ulpgc.es/moodle4test/lib/requirejs.php/1685461410/core/event.js:5189
    execCb https://cvdev.ulpgc.es/moodle4test/lib/javascript.php/1685461410/lib/requirejs/require.min.js:5
    check https://cvdev.ulpgc.es/moodle4test/lib/javascript.php/1685461410/lib/requirejs/require.min.js:5
    f https://cvdev.ulpgc.es/moodle4test/lib/javascript.php/1685461410/lib/requirejs/require.min.js:5
    each https://cvdev.ulpgc.es/moodle4test/lib/javascript.php/1685461410/lib/requirejs/require.min.js:5
    f https://cvdev.ulpgc.es/moodle4test/lib/javascript.php/1685461410/lib/requirejs/require.min.js:5
    f https://cvdev.ulpgc.es/moodle4test/lib/javascript.php/1685461410/lib/requirejs/require.min.js:5
    each https://cvdev.ulpgc.es/moodle4test/lib/javascript.php/1685461410/lib/requirejs/require.min.js:5
    f https://cvdev.ulpgc.es/moodle4test/lib/javascript.php/1685461410/lib/requirejs/require.min.js:5
    f https://cvdev.ulpgc.es/moodle4test/lib/javascript.php/1685461410/lib/requirejs/require.min.js:5
    each https://cvdev.ulpgc.es/moodle4test/lib/javascript.php/1685461410/lib/requirejs/require.min.js:5
    f https://cvdev.ulpgc.es/moodle4test/lib/javascript.php/1685461410/lib/requirejs/require.min.js:5
    f https://cvdev.ulpgc.es/moodle4test/lib/javascript.php/1685461410/lib/requirejs/require.min.js:5
    each https://cvdev.ulpgc.es/moodle4test/lib/javascript.php/1685461410/lib/requirejs/require.min.js:5
    f https://cvdev.ulpgc.es/moodle4test/lib/javascript.php/1685461410/lib/requirejs/require.min.js:5
    l https://cvdev.ulpgc.es/moodle4test/lib/javascript.php/1685461410/lib/requirejs/require.min.js:5
    each https://cvdev.ulpgc.es/moodle4test/lib/javascript.php/1685461410/lib/requirejs/require.min.js:5
    l https://cvdev.ulpgc.es/moodle4test/lib/javascript.php/1685461410/lib/requirejs/require.min.js:5
    completeLoad https://cvdev.ulpgc.es/moodle4test/lib/javascript.php/1685461410/lib/requirejs/require.min.js:5
    onScriptLoad https://cvdev.ulpgc.es/moodle4test/lib/javascript.php/1685461410/lib/requirejs/require.min.js:5

**Comment by marcusgreen** [comment] 2023-05-30 16:31
I expect you have already tried this but can you confirm you have purged caches?

**Comment by marcusgreen** [comment] 2023-05-30 21:39
As I just commented in the context related ticket, this is interesting. I just setup a fresh Moodle 4.2, installed the plugin and as you said, it broke all the javascript everywhere all at once. Commenting out the call to that javascript in the PHP didn't make it go away (or purging caches afterwards). The only fix was to delete the amd/build folder. As this is not essential to the plugin and it depends on jquery which will be removed from Moodle within a few versions, I will remove this capability from the plugin. I cannot give any timescale however.

**Comment by mattgig** [comment] 2023-06-11 13:10
I had exactly the same problem in one of my installations (Moodle 4.2). As soon as the plugin is installed, it breaks the navigation on all pages through a JavaScript error. 
I could then replicate the problem in two instances by adding respectively removing the plugin.
Removing the AMD folder also solved the problem.

**Comment by marcusgreen** [comment] 2023-06-11 22:16
Thanks Mattias. I am away all this week (at MoodleDach). I will look into this when I return.

**Comment by sarahjcotton** [comment] 2023-06-20 10:34
Hi Marcus

I have also come across this issue in Moodle 4.1.4 (Build: 20230612)] and have removed the plugin for the time being. I appreciate you have been away but do you happen to have any idea of an eta for a fix at all?

Many thanks
Sarah

**Comment by izendegi** [comment] 2023-06-22 07:56
Hi,

We've been testing this plugin without issues on Moodle 4.1 until we've installed 4.1.4 and then we've suffered this issue both with Boost and other Boost based themes; maybe looking at the core changes of the last minor gives you a clue about the cause:

https://moodledev.io/general/releases/4.1/4.1.4

**Comment by marcusgreen** [comment] 2023-06-22 08:12
I was at MootDACH last week and have discussed this with Sarah who posted above. Prior to 4.X there were intermittent problems, since 4.X there have been widespread problems with this. My solution is to remove the datatables functionality and code. It was always more a "nice to have" than essential. I will post here when I start work on it. I will included the missing get_strings as well.

**Comment by marcusgreen** [comment] 2023-08-13 08:19
I am closing this ticket as the latest release has removed datatables both to fix this problem and because Moodle is moving away from any use of JQuery. If anyone would like to provide a pull/fork that keeps this I will attempt to maintain a paralell branch with that support. I won't put it in the main branch for deployment to moodle.org as I feel it is likely to trigger more support than I am willing to do. Thank you for your feedback.

**Closed by marcusgreen** 2023-08-13 08:19 UTC
